---

services:
  bitmask_vpn:
    build: docker_bitmask
    container_name: bitmask_vpn
    env_file: [ ".env" ]
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    devices: [ "/dev/net/tun" ]
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    mem_limit: 5g
    mem_reservation: 5g
    restart: always
    ports:
      # transmission ports
      - 127.0.0.1:9093:9091

  transmission:
#    image: lscr.io/linuxserver/transmission:latest
    build: docker_transmission
    container_name: transmission
    env_file: [ ".env" ]
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    network_mode: "service:bitmask_vpn"
    depends_on: [bitmask_vpn]
    volumes:
      - "${TRANSMISSION_DOWNLOAD_DIR}:/downloads"
      - "${TRANSMISSION_DOWNLOAD_DIR}/config:/config"
    mem_limit: 5g
    mem_reservation: 5g
    restart: always